const express = require('express')
const router = express.Router()
const courseController = require('../app/controllers/course.controller')

router.get('/get-all-course', courseController.getAllCourse)
router.get('/get-course-by-name/:course_name', courseController.getCourseByName)
router.get('/continues-learn-course-by-id/:member_id/:course_id', courseController.memberContinuesLearnCourseById)
router.get('/enroll-course/:member_id/:course_id/:enroll_version', courseController.createMemberEnrollmentCourse)
router.post('/submit-mooc-course', courseController.submitCourse)
router.get('/get-course-detail-by-id/:course_id', courseController.getCourseDetailByID)
router.get('/check-enrollment-course/:member_id/:course_id/:enroll_version', courseController.checkEnrollmentCourse)
// router.get('/get-course-by-course_id-and-version/:course_id/:version', courseController.getCourseByCourseIdAndVersion)
router.get('/get-all-course-follow-course-enrollment-by-member-id/:member_id', courseController.getAllCourseFollowCourseEnrollmentByMemberId)
router.get('/get-all-course-for-member-by-member-id/:member_id', courseController.getAllCourseForMemberByMemberId)
router.get('/get-learning-process-by-course-id-and-member-id/:member_id/:course_id', courseController.getLearningProcessByCourseIdAndMemberId)
module.exports = router